# Generated by Django 4.1.6 on 2023-02-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('jersey', models.IntegerField(db_column='Jersey')),
                ('team', models.CharField(db_column='Team', max_length=50)),
                ('nationality', models.CharField(db_column='Nationality', max_length=50)),
            ],
            options={
                'db_table': 'Player',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('number', models.OneToOneField(db_column='Number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Nba.player')),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('wins', models.IntegerField(db_column='Wins')),
                ('points', models.IntegerField(db_column='Points')),
                ('rebounds', models.IntegerField(db_column='Rebounds')),
                ('assists', models.IntegerField(db_column='Assists')),
            ],
            options={
                'db_table': 'Stat',
            },
        ),
    ]
