# Generated by Django 4.1.6 on 2023-02-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='pro_stats',
            field=models.IntegerField(db_column='Pro_stats', default=0),
            preserve_default=False,
        ),
    ]
