# Generated by Django 4.1.6 on 2023-02-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nba', '0002_stat_pro_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(db_column='data', max_length=50)),
                ('team1', models.CharField(db_column='team1', max_length=50)),
                ('team2', models.CharField(db_column='team2', max_length=50)),
                ('score', models.IntegerField(db_column='score')),
            ],
            options={
                'db_table': 'GameStat',
            },
        ),
        migrations.RemoveField(
            model_name='stat',
            name='pro_stats',
        ),
    ]
