# Generated by Django 4.1.6 on 2023-02-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nba', '0003_gamestat_remove_stat_pro_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestat',
            name='data',
            field=models.DateField(db_column='Date'),
        ),
    ]
